# Asian Population
SELECT SUM(CITY.POPULATION)
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT = 'Asia';

# African Cities
SELECT CITY.NAME
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT = 'Africa';

# Average Population of Each Continent
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
GROUP BY COUNTRY.CONTINENT;

# The Report
SELECT IF (GRADES.GRADE > 7, STUDENTS.NAME, NULL) AS NAME_S, GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS
INNER JOIN GRADES ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND MAX_MARK
ORDER BY GRADES.GRADE DESC, NAME_S ASC, STUDENTS.MARKS ASC;